steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--build-arg', 'REACT_APP_BACKEND_URL=$_BACKEND_URL', '-t', 'gcr.io/plan-my-concert/patidevgcp-frontend', '.' ]
  
  # 2. Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/plan-my-concert/patidevgcp-frontend' ]
  
  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'patidevgcp-frontend', '--image', 'gcr.io/plan-my-concert/patidevgcp-frontend', '--region', 'asia-south1', '--allow-unauthenticated' ]

images:
  - 'gcr.io/plan-my-concert/patidevgcp-frontend'
